---
  title: "Schedule of Topics"
  output: html_document
---

Week | Topic | Material
:- | :----- | :-----
1 | Introduction and Basic Concepts | moment statistics, distributions, transformations, t-test, correlation, chi-square, Dean's roadmap of inferential statistics
2 | Resampling | randomization, bootstrap, jackknife, Monte Carlo methods
3 | ANOVA MOdels | single factor, factorial, nested and mixed models, pairwise comparisons, type I, II, and III SS
4 | Regression Models | regression, multiple regression, analysis of covariance (ANCOVA)
5 | Matrix Algebra and LM | review of matrix algebra; deriving the linear model in matrix form
6 | Multivariate Data and the GLM| properties of multivariate data and data spaces, distance measures and metrics, MANOVA, MANCOVA, 
7 | Interactions and Patterns of Change | interpreting GLM interaction terms, understanding what causes significant interactions, dissecting patterns of change
8 | Ordination | principal components analysis (PCA), and related approaches: principal coordinates (PCoA), multidimensional scaling (MDS), canonical variates/discriminant function analysis (CVA/DFA), correspondence analysis (CA)
9 | Clustering | SAHN methods (UPGMA, WPGMA, etc.), K-means clustering
10 | Multivariate Association and Canonical Ordination | Mantel tests, canonical correlation, partial least squares, RV coefficient, CVA, canonical correspondence analysis (CCA), redundancy analysis (RDA)
11 | Model Comparisons | AIC, BIC, LRT methods
12 | Phylogenetic Comparative Methods | phylogenetic non-independence, phylogenetically independent contrasts (PIC), phylogenetic anova/regression (PGLS), phylogenetic signal, rates of evolution
13 | Spatial Statistics | point patterns, autocorrelation, correlograms/semivariograms, spatial non-independence (in GLS)
14 | Meta-Analysis | combining results across studies, effect sizes, summary analyses, graphical approaches (funnel plots, etc.)
